<?php echo $this->doctype() . "\r\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <script type="text/javascript">
            urlBaseCkeditor = '<?php echo $this->baseUrl(); ?>/scripts/ckeditor/';
            //  ...
        </script>
        <?php
        echo $this->headMeta() . "\r\n";
        echo $this->headTitle() . "\r\n";
        ?>
    </head>

    <body>
        <div id="contener">
            <div id="header">
            </div>
            <div id="content">
                <div id="menu">
                </div>

                <div id="contenu">

                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
            <div id="footer">
                <?php
                $auth = $this->isAuth();
                if ($auth) { 
                    echo 'Bonjour '. $auth[0]->account_name. ' | Mon compte | <a href="'. SITE_URL . 'play">Play</a> | <a href="'. SITE_URL . 'home/auth/logout">Déconnexion</a>';
                 } ?>
            </div>
        </div>
    </body>

</html>
